#ifndef __APP_SCREEN_TYPE_H
#define __APP_SCREEN_TYPE_H

typedef enum
{
	SCREEN_TYPE_OVERVIEW = 0,
	SCREEN_TYPE_TEMP_HUMI,
	SCREEN_TYPE_PRESSURE,
	SCREEN_TYPE_LIGHT,
	SCREEN_TYPE_COUNT
} ScreenType;

#endif
